### ISSUE TITLE
ship arm64 binary

### ISSUE THREAD

**Issue by realies** [parcel-bundler/watcher#130]

**Comment by mischnic** [comment]
Linux arm64?

**Comment by realies** [comment]
@mischnic, linux and darwin would be great

**Comment by mischnic** [comment]
Darwin should already exist: https://unpkg.com/browse/@parcel/watcher@2.1.0/prebuilds/
You might be using the watcher outside of Parcel itself, but we should ideally just have prebuilds for the same platforms that the other native Parcel packages support as well: https://unpkg.com/browse/@parcel/hash@2.8.3/

**Comment by dargmuesli** [comment]
It's great that Darwin prebuilts already exist! If one is running Linux containers on arm64-Darwin though, no arm64 prebuilts for Linux can be found. The fallback to build with Python makes it necessary to download much larger Docker images than necessary if a prebuilt was available.
I went ahead and created a #132 to try to resolve this issue :raised_hands:

**Comment by gustaff-weldon** [comment]
This is affecting us and preventing from upgrades of dependencies that use `parcel-bundler`

**Comment by dsalaza4** [comment]
We're also being affected by this. Please review the opened PR!

**Comment by rickardp** [comment]
This blocks building in containers on Apple Silicon macs, as well as the transition to ARM64 build agents (the latter becomes important for cost reasons). Any reason for not 

> Darwin should already exist: https://unpkg.com/browse/@parcel/watcher@2.1.0/prebuilds/ You might be using the watcher outside of Parcel itself, but we should ideally just have prebuilds for the same platforms that the other native Parcel packages support as well: https://unpkg.com/browse/@parcel/hash@2.8.3/

There seems to be a PR open already. I can't judge if it works or not since I cannot see it being run on AZDO. It also lacks support for glibc linux but assuming Alpine works it should be trivial to add. Any reason not to proceed with this?
