### ISSUE TITLE
Replace libuv usage with napi_async_work?

### ISSUE THREAD

**Issue by littledivy** [parcel-bundler/watcher#96]
Hi! I'm working on a N-API implementation on top of deno_core and Tokio (https://github.com/littledivy/napi-rusty-v8/) and we're trying to get all of parcel's native modules to work. The implementation is eventually going to be merged in Deno. 

Since this is built on top of Tokio, we're avoiding to expose libuv _polyfills_. This makes `@parcel/watcher` incompatible. Would it be possible to use napi_async_work instead of libuv for the Watcher?

**Comment by devongovett** [comment]
Last I checked (which was a few years ago, so may have changed), there was no equivalent of `uv_async_send` as used here: https://github.com/parcel-bundler/watcher/blob/caf372c41abff401a60dde698891631e3387ee77/src/Watcher.cc#L92

This is different from `napi_async_work`, because we execute a JS callback multiple times. We use `uv_async_send` to call into the JS thread from a background thread where watching is occurring.

Are you aware of a way to do this with napi?

**Comment by littledivy** [comment]
Oh yeah, for `uv_async_t` there is [`Napi::ThreadSafeFunction`](https://github.com/nodejs/node-addon-api/blob/master/doc/threadsafe_function.md)
